SET SCHEMA MONITOR;

INSERT INTO ITEM_TYPE (ID, NAME) VALUES (1, 'Temperature');
INSERT INTO ITEM_TYPE (ID, NAME) VALUES (2, 'Humidity');
INSERT INTO ITEM_TYPE (ID, NAME) VALUES (3, 'Switch');
INSERT INTO ITEM_TYPE (ID, NAME) VALUES (4, 'Voltage');

-- UTF-8 DEGREE CELSIUS' (0x2103)

-- SENSOR ITEMS

INSERT INTO SENSOR (ID, NODE, VALUE, UNIT, ITEM_TYPE, TIME, NAME, TOPIC) VALUES(1, 'ESP_18BE43', 0.0, char(0x2103), 1, now(), 'Hallway', null);
INSERT INTO SENSOR (ID, NODE, VALUE, UNIT, ITEM_TYPE, TIME, NAME, TOPIC) VALUES(2, 'ESP_18BE43', 0.0, '%', 2, now(), 'Hallway', null);
INSERT INTO SENSOR (ID, NODE, VALUE, UNIT, ITEM_TYPE, TIME, NAME, TOPIC) VALUES(5, 'ESP_18BE43', 0.0, 'V', 4, now(), 'Hallway', null);

INSERT INTO SENSOR (ID, NODE, VALUE, UNIT, ITEM_TYPE, TIME, NAME, TOPIC) VALUES(10, 'ESP_296715', 0.0, char(0x2103), 1, now(), 'Bedroom', null);
INSERT INTO SENSOR (ID, NODE, VALUE, UNIT, ITEM_TYPE, TIME, NAME, TOPIC) VALUES(11, 'ESP_296715', 0.0, 'V', 4, now(), 'Bedroom', null);

INSERT INTO SENSOR (ID, NODE, VALUE, UNIT, ITEM_TYPE, TIME, NAME, TOPIC) VALUES(21, 'ESP_18BB1E', 0.0, char(0x2103), 1, now(), 'Living', null);
INSERT INTO SENSOR (ID, NODE, VALUE, UNIT, ITEM_TYPE, TIME, NAME, TOPIC) VALUES(22, 'ESP_18BB1E', 0.0, '%', 2, now(), 'Living', null);
INSERT INTO SENSOR (ID, NODE, VALUE, UNIT, ITEM_TYPE, TIME, NAME, TOPIC) VALUES(23, 'ESP_18BB1E', 0.0, 'V', 4, now(), 'Living', null);

--  SWITCH ITEMS

INSERT INTO SWITCH (ID, NODE, VALUE, UNIT, ITEM_TYPE, TIME, NAME, TOPIC) VALUES(1, 'ESP_XXYYZZ', 0, 'X', 3, now(), 'ROOM 1', null);

