INSERT INTO PUBLIC.APP_USER (ID, USERNAME, PASSWORD) VALUES ('1', 'admin', '$2a$10$GHNfGU9mbW0lT4qkOuUdF.0GdT0TKcVy6HU2ct5AFELpfsOOOvPxe'); -- com.zetaemmesoft.auth.utils.PasswordEncoderGenerator
INSERT INTO PUBLIC.APP_USER (ID, USERNAME, PASSWORD) VALUES ('2', 'marco', '$2a$10$GHNfGU9mbW0lT4qkOuUdF.0GdT0TKcVy6HU2ct5AFELpfsOOOvPxe');
INSERT INTO PUBLIC.APP_USER (ID, USERNAME, PASSWORD) VALUES ('3', 'guest', '$2a$10$GHNfGU9mbW0lT4qkOuUdF.0GdT0TKcVy6HU2ct5AFELpfsOOOvPxe');

INSERT INTO PUBLIC.APP_ROLE (ID, ROLENAME) VALUES ('1', 'ADMIN_USER');
INSERT INTO PUBLIC.APP_ROLE (ID, ROLENAME) VALUES ('2', 'POWER_USER');
INSERT INTO PUBLIC.APP_ROLE (ID, ROLENAME) VALUES ('3', 'GUEST_USER');

-- admin
INSERT INTO PUBLIC.APP_USER_ROLE(USER_ID, ROLE_ID) VALUES('1', '1');
INSERT INTO PUBLIC.APP_USER_ROLE(USER_ID, ROLE_ID) VALUES('1', '2');
INSERT INTO PUBLIC.APP_USER_ROLE(USER_ID, ROLE_ID) VALUES('1', '3');

-- marco
INSERT INTO PUBLIC.APP_USER_ROLE(USER_ID, ROLE_ID) VALUES('2', '2');

-- guest
INSERT INTO PUBLIC.APP_USER_ROLE(USER_ID, ROLE_ID) VALUES('3', '3');
